/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hredwan.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Registration service. Represents a row in the &quot;Registration_Registration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hredwan.registration.model.impl.RegistrationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hredwan.registration.model.impl.RegistrationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Registration
 * @generated
 */
@ProviderType
public interface RegistrationModel extends BaseModel<Registration> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registration model instance should use the {@link Registration} interface instead.
	 */

	/**
	 * Returns the primary key of this registration.
	 *
	 * @return the primary key of this registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this registration.
	 *
	 * @param primaryKey the primary key of this registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the registration ID of this registration.
	 *
	 * @return the registration ID of this registration
	 */
	public long getRegistrationId();

	/**
	 * Sets the registration ID of this registration.
	 *
	 * @param registrationId the registration ID of this registration
	 */
	public void setRegistrationId(long registrationId);

	/**
	 * Returns the name of this registration.
	 *
	 * @return the name of this registration
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this registration.
	 *
	 * @param name the name of this registration
	 */
	public void setName(String name);

	/**
	 * Returns the surname of this registration.
	 *
	 * @return the surname of this registration
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this registration.
	 *
	 * @param surname the surname of this registration
	 */
	public void setSurname(String surname);

	/**
	 * Returns the date of birth of this registration.
	 *
	 * @return the date of birth of this registration
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this registration.
	 *
	 * @param dateOfBirth the date of birth of this registration
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the email of this registration.
	 *
	 * @return the email of this registration
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this registration.
	 *
	 * @param email the email of this registration
	 */
	public void setEmail(String email);

	/**
	 * Returns the registration date of this registration.
	 *
	 * @return the registration date of this registration
	 */
	public Date getRegistrationDate();

	/**
	 * Sets the registration date of this registration.
	 *
	 * @param registrationDate the registration date of this registration
	 */
	public void setRegistrationDate(Date registrationDate);

	@Override
	public Registration cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}